name: SurvivalPlugin
version: 1.1
main: org.javierdz.survivalprueba.SurvivalPrueba
author: Javierdz
commands:
  help:
    description: Show help
    usage: /help

  s:
    description: Teleport a player to you
    usage: /s

  survival:
    description: Main plugin command
    usage: /survival

  events:
    description: Show events
    usage: /events

  gms:
    description: Set gamemode to survival
    usage: /gms <player>

  gmc:
    description: Set gamemode to creative
    usage: /gmc <player>

  bc:
    description: Broadcast player's coordinates to the server
    usage: /bc