name: SurvivalPlugin
version: 1.0
main: org.javierdz.survivalprueba.SurvivalPrueba
author: Javierdz
commands:
  help:
    description: Show help
    usage: /help

  s:
    description: Teleport a player to you
    usage: /s <player>
  survival:
    description: Main plugin command
    usage: /survival
